version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: math_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
    depends_on:
      - rabbitmq
    networks:
      - mathnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: math_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - mathnet

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"       # AMQP (бекенд)
      - "15672:15672"     # панель RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - mathnet

networks:
  mathnet:
    driver: bridge
